version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:edge
    working_directory: /home/builder/secure
    steps:
      - run:
          name: Initialize
          command: df -hlT
