version: 2.1
jobs:
  build:
    docker:
      - image: nvidia/cuda:11.3.0-devel-ubuntu20.04
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKERHUB_TOKEN"
    #working_directory: /home/builder/secure
    steps:
      - run:
          name: Add App
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -qy
            apt-get -qy --no-install-recommends install bash git-core build-essential gcc clang llvm curl ca-certificates libva-dev python3
            curl https://rclone.org/install.sh | bash
            mkdir -p ~/.config/rclone
            curl -sL ${RCLONE_GDRIVE_CONFIG_URL} >> ~/.config/rclone/rclone.conf
      - run:
          name: Git Auth
          command: |
            export GitHubMail GitHubName GITHUB_TOKEN
            git config --global user.email "$GitHubMail"
            git config --global user.name "$GitHubName"
            git config --global credential.helper store
            git config --global color.ui true
            git clone -q "https://$GITHUB_TOKEN@github.com/$GitHubName/google-git-cookies.git" &> /dev/null
            if [ -e google-git-cookies ]; then
              bash google-git-cookies/setup_cookies.sh
              rm -rf google-git-cookies
            fi
      - run:
          name: Initialize
          command: |
            mkdir -p /opt/ffmpeg_build
            chmod 777 /opt/ffmpeg_build -R
            cd /opt/ffmpeg_build
            curl -sL https://github.com/rokibhasansagar/ffmpeg-build-script/raw/updates/build-ffmpeg -O
            chmod a+x build-ffmpeg
            NUMJOBS=9 SKIPINSTALL=yes ./build-ffmpeg --build --enable-gpl-and-non-free --full-static || exit 1
            for i in ffmpeg ffplay ffprobe; do
              rclone copy ./workspace/bin/${i} td:/ffmpeg_build6/ --progress
            done

workflows:
  version: 2
  workstation:
    jobs:
      - build:
          context: org-global
