version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder-beta:focal
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKERHUB_TOKEN"
    working_directory: /home/builder/secure
    steps:
      - run:
          name: Git Auth
          command: |
            export GitHubMail GitHubName GITHUB_TOKEN
            git config --global user.email "$GitHubMail"
            git config --global user.name "$GitHubName"
            git config --global credential.helper store
            git config --global color.ui true
            git clone -q "https://$GITHUB_TOKEN@github.com/$GitHubName/google-git-cookies.git" &> /dev/null
            if [ -e google-git-cookies ]; then
              bash google-git-cookies/setup_cookies.sh
              rm -rf google-git-cookies
            fi
      - run:
          name: Initialize
          command: df -hlT
workflows:
  version: 2
  workstation:
    jobs:
      - build:
          context: org-global
